### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by flamendless** [tsteinholz/LoveShaderConverter#3]
Im following the tutorial,error in the terminal :

`
./LoveShaderConverter: No such file or directory
`

Im using linux, xubuntu

**Comment by tsteinholz** [comment]
The command takes an argument of the file you want to use. example usage:
```
LoveShaderConverter <FileName>
```

**Comment by flamendless** [comment]
It says command is not found

**Comment by tsteinholz** [comment]
Hm, Are you running it in the right directory? If you are there might be an architecture problem, is your computer 32bit?

**Comment by tsteinholz** [comment]
The architecture for your gcc might be different from your computer. For example having a 64bit compiler on a 32bit OS.

**Comment by flamendless** [comment]
i have a 64 bit pc.

**Comment by flamendless** [comment]
im also running it inside the directory

**Comment by tsteinholz** [comment]
Well if you are getting the error that there is no file or directory, you are either not executing the binary at all or it is not on the right platform. I don't have enough information to help you beyond that.

**Comment by tsteinholz** [comment]
You can also try downloading the releases and seeing if you can execute those binaries.
